---
- name: python-pam dependencies
  yum:
    name: pam-devel

- name: Install python-pam and other keystone-auth dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - python-pam
    - python-memcached
    - sphinx

- name: Download pam-python
  get_url:
    url: https://downloads.sourceforge.net/project/pam-python/pam-python-1.0.6-1/pam-python-1.0.6.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fpam-python%2Ffiles%2Fpam-python-1.0.6-1%2F&ts=1510755052&use_mirror=netcologne
    dest: /root/pam-python-1.0.6.tar.gz

- name: Extract pam-python
  unarchive:
    src: /root/pam-python-1.0.6.tar.gz
    dest: /root/
    remote_src: yes

- name: Build and Install python-pam
  shell: |
      cd src
      python setup.py install
      cd ..
      make
      cp src/pam_python.so /usr/lib64/security/pam_python.so
  args:
    chdir: /root/pam-python-1.0.6
    creates: /usr/lib64/security/pam_python.so

- name: Install keystone-auth pam
  get_url:
    url: https://raw.githubusercontent.com/stackhpc/pam-keystone/ef863a13592a7e7f87b2fc48e1d86187155ce6a5/keystone-auth.py
    dest: /usr/lib64/security/
    mode: 0555

- name: Get selinux policy violation capture
  copy:
    src: pam-python-selinux-capture
    dest: /root/pam-python-1.0.6/pam-python-selinux-capture

- name: Generate and install se-linux module
  shell: |
      cat pam-python-selinux-capture | audit2allow -M keystone-pam
      semodule -i keystone-pam.pp
  args:
    chdir: /root/pam-python-1.0.6
    creates: /root/pam-python-1.0.6/keystone-pam.pp

- name: Update PAM auth configuration
  lineinfile:
    create: no
    state: present
    insertbefore: "auth *sufficient *pam_unix.*"
    line: "auth        sufficient    pam_python.so /usr/lib64/security/keystone-auth.py {{ keystone_user_os_config_name_pam }}"
    path: "{{ item }}"
  with_items:
    - /etc/pam.d/system-auth-ac
    - /etc/pam.d/password-auth-ac

- name: Enable PasswordAuthentication in SSH config
  lineinfile:
    path: /etc/ssh/sshd_config
    create: no
    state: present
    insertafter: "^#PasswordAuthentication.*"
    regexp: "^PasswordAuthentication .*"
    line: "PasswordAuthentication yes"
  notify:
    - Restart SSH
